const SYMBOLS=[
{symbol:"Water",themes:["emotion","change","depth"],meaning:"Often reflects emotional life, uncertainty, cleansing, or movement through change."},
{symbol:"House",themes:["self","memory","identity"],meaning:"May represent the dreamer, the mind, family life, or different parts of the self."},
{symbol:"Flying",themes:["freedom","control","escape"],meaning:"Can suggest liberation, confidence, ambition, avoidance, or a wish to rise above pressure."},
{symbol:"Teeth",themes:["confidence","loss","communication"],meaning:"Frequently linked with vulnerability, self-image, speech, transition, or fear of losing control."},
{symbol:"Snake",themes:["change","danger","healing"],meaning:"May indicate threat, transformation, instinct, renewal, or concealed knowledge."},
{symbol:"Road",themes:["direction","choice","journey"],meaning:"Often relates to life direction, decisions, progress, delay, or uncertainty about what comes next."},
{symbol:"Storm",themes:["conflict","release","overwhelm"],meaning:"Can represent emotional turbulence, mounting pressure, disruption, or an approaching release."},
{symbol:"Door",themes:["opportunity","boundary","transition"],meaning:"May suggest access, exclusion, new possibilities, guarded feelings, or movement into a new phase."},
{symbol:"Animal",themes:["instinct","relationship","trait"],meaning:"Often reflects instinctive qualities, emotional bonds, fears, or traits associated with that animal."}];
const $=id=>document.getElementById(id);const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function detect(text){const x=text.toLowerCase();return SYMBOLS.filter(s=>x.includes(s.symbol.toLowerCase()))}
function interpret(text,emotion,context){const m=detect(text),themes=[...new Set(m.flatMap(x=>x.themes))];const symbols=m.length?m.map(x=>`<li><strong>${x.symbol}:</strong> ${x.meaning}</li>`).join(""):"<li>No exact starter symbol matched. Focus on the most emotionally charged image and what it means in your own life.</li>";return `<h3>Possible themes</h3><p>This dream may be touching on <strong>${themes.slice(0,5).join(", ")||"identity, transition, emotion, and personal meaning"}</strong>. The strongest emotion was <strong>${esc(emotion)}</strong>, which may matter more than a universal symbol definition.</p><h3>Symbols noticed</h3><ul>${symbols}</ul><h3>Personal-context prompt</h3><p>${context?`Compare the dream with: <em>${esc(context)}</em>`:"Consider what was happening in your life within the previous few days, especially unresolved decisions or strong emotions."}</p><h3>Questions to reflect on</h3><ul><li>What felt most vivid?</li><li>Where in waking life do you feel a similar emotion?</li><li>Did you gain or lose control?</li><li>What changed from beginning to end?</li></ul>`}
function getJournal(){try{return JSON.parse(localStorage.getItem("somneiros-journal")||"[]")}catch{return[]}}function setJournal(x){localStorage.setItem("somneiros-journal",JSON.stringify(x));renderJournal()}
function renderJournal(){const a=getJournal();$("journalList").innerHTML=a.length?a.map((e,i)=>`<article class="journal-entry"><h3>${esc(e.title||"Untitled dream")}</h3><div class="entry-meta">${new Date(e.createdAt).toLocaleString()} • ${esc(e.emotion)} • intensity ${esc(e.intensity)}/5</div><p>${esc(e.text.slice(0,240))}${e.text.length>240?"…":""}</p><div class="entry-actions"><button data-view="${i}">View</button><button data-delete="${i}">Delete</button></div></article>`).join(""):`<div class="journal-entry"><p>No dreams saved yet.</p></div>`}
$("dreamForm").addEventListener("submit",e=>{e.preventDefault();const entry={title:$("dreamTitle").value.trim()||"Untitled dream",text:$("dreamText").value.trim(),emotion:$("emotion").value,intensity:$("intensity").value,context:$("lifeContext").value.trim(),createdAt:new Date().toISOString()};$("resultTitle").textContent=entry.title;$("resultBody").innerHTML=interpret(entry.text,entry.emotion,entry.context);$("resultCard").hidden=false;$("resultCard").scrollIntoView({behavior:"smooth"});if($("saveDream").checked){const a=getJournal();a.unshift(entry);setJournal(a.slice(0,100))}});
$("journalList").addEventListener("click",e=>{const a=getJournal();if(e.target.dataset.view!==undefined){const x=a[+e.target.dataset.view];$("resultTitle").textContent=x.title;$("resultBody").innerHTML=interpret(x.text,x.emotion,x.context||"");$("resultCard").hidden=false;$("resultCard").scrollIntoView({behavior:"smooth"})}if(e.target.dataset.delete!==undefined){a.splice(+e.target.dataset.delete,1);setJournal(a)}});
$("exportButton").onclick=()=>{const b=new Blob([JSON.stringify(getJournal(),null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="somneiros-dream-journal.json";a.click();URL.revokeObjectURL(u)};$("clearButton").onclick=()=>{if(confirm("Delete all locally saved dreams?"))setJournal([])};
function renderSymbols(q=""){q=q.toLowerCase();const f=SYMBOLS.filter(x=>x.symbol.toLowerCase().includes(q)||x.themes.join(" ").includes(q)||x.meaning.toLowerCase().includes(q));$("symbolGrid").innerHTML=f.map(x=>`<article class="symbol-card"><h3>${x.symbol}</h3><span class="eyebrow">${x.themes.join(" • ")}</span><p>${x.meaning}</p></article>`).join("")||"<p>No matching starter symbol.</p>"}$("symbolSearch").oninput=e=>renderSymbols(e.target.value);
const drawer=$("drawer"),scrim=$("scrim");function toggle(open){drawer.classList.toggle("open",open);drawer.setAttribute("aria-hidden",String(!open));scrim.hidden=!open}$("menuButton").onclick=()=>toggle(true);$("closeDrawer").onclick=()=>toggle(false);scrim.onclick=()=>toggle(false);drawer.querySelectorAll("a").forEach(a=>a.onclick=()=>toggle(false));
const saved=localStorage.getItem("somneiros-theme");if(saved)document.documentElement.dataset.theme=saved;$("themeButton").onclick=()=>{const n=document.documentElement.dataset.theme==="light"?"dark":"light";document.documentElement.dataset.theme=n;localStorage.setItem("somneiros-theme",n)};
let prompt;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();prompt=e;$("installButton").hidden=false});$("installButton").onclick=async()=>{if(!prompt)return;prompt.prompt();await prompt.userChoice;prompt=null;$("installButton").hidden=true};if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));renderJournal();renderSymbols();
